Gen2 common objdet
luxonis/depthai-shared pull request #13
Opened 2021-01-05 20:12 UTC by jonngai

2021-01-06 11:36 UTC, themarpe requested changes

2021-01-06 11:36 UTC, themarpe commented on include/depthai-shared/datatype/DetectionNetworkTypeEnum.hpp
> +enum DetectionNetworkTypeEnum { dntype_yolo, dntype_mobilenet };
Move and rename the file to: `include/depthai-shared/pb/common/DetectionNetworkType.hpp`

And modify to enum class:
```
enum class DetectionNetworkType { YOLO, MOBILENET };
```

2021-01-06 11:36 UTC, themarpe commented on include/depthai-shared/pb/properties/CommonObjDetProperties.hpp
> +#pragma once
CommonObjDetProperties.hpp file still needed?

2021-01-06 21:29 UTC, jonngai commented on include/depthai-shared/pb/properties/CommonObjDetProperties.hpp
> +#pragma once
thanks. deleted.

2021-01-06 23:28 UTC, jonngai commented on include/depthai-shared/datatype/DetectionNetworkTypeEnum.hpp
> +enum DetectionNetworkTypeEnum { dntype_yolo, dntype_mobilenet };
sure. done.

2021-01-07 22:51 UTC, themarpe approved these changes

2021-01-07 22:55 UTC, themarpe approved these changes
Feel free to merge after other PRs are resolved as well

2021-01-08 01:40 UTC, themarpe commented on include/depthai-shared/pb/properties/DetectionNetworkProperties.hpp
> +    std::string streamName;
I think this is redundant?

2021-01-11 12:46 UTC, themarpe requested changes
In DatatypeEnum.cpp change `hierarchy` to:
```
const std::unordered_map<DatatypeEnum, std::vector<DatatypeEnum>> hierarchy = {
    {DatatypeEnum::Buffer, {DatatypeEnum::ImgFrame, DatatypeEnum::NNData, DatatypeEnum::ImageManipConfig, DatatypeEnum::ImgDetections, DatatypeEnum::CameraControl}},
    {DatatypeEnum::ImgFrame, {}},
    {DatatypeEnum::NNData, {}},
    {DatatypeEnum::ImageManipConfig, {}},
    {DatatypeEnum::ImgDetections, {}},
    {DatatypeEnum::CameraControl, {}}};
```

2021-01-12 20:54 UTC, merged