Add has autofocusIC
luxonis/depthai-shared pull request #148
Opened 2023-08-24 11:05 UTC by AnielAlexa

2023-08-24 15:17 UTC, themarpe requested changes

2023-08-24 15:17 UTC, themarpe commented on include/depthai-shared/common/CameraFeatures.hpp
> +     *  Autofocus based on lensposition/boardconfig
```suggestion
     *  Whether camera has auto focus capabilities, or is a fixed focus lens
```

2023-08-24 22:31 UTC, szabi-luxonis reviewed
Open PR on FW too

2023-08-25 16:14 UTC, themarpe approved these changes

2023-08-31 01:42 UTC, closed without merging