Message groups
luxonis/depthai-shared pull request #152
Opened 2023-11-02 16:39 UTC by asahtik

Implemented the RawMessageGroup datatype

2023-11-03 12:54 UTC, themarpe requested changes

2023-11-03 12:54 UTC, themarpe commented on include/depthai-shared/datatype/RawMessageGroup.hpp
> +    }
Necessary?

2023-11-10 11:11 UTC, moratom approved these changes
LGTM after changes are made & clang-format is run.

2023-11-10 11:11 UTC, moratom commented on include/depthai-shared/properties/SyncProperties.hpp
> +    int numFramesPool = 3;
Let's bump that to 8, what needs to be allocated here is small anyways.

2023-11-10 11:19 UTC, moratom commented on include/depthai-shared/properties/SyncProperties.hpp
> +    uint32_t syncAttempts = 50;
Change to int32_t and to -1 by default (see the core review)

2023-11-20 12:33 UTC, szabi-luxonis commented on include/depthai-shared/properties/SyncProperties.hpp
> +    uint64_t syncIntervalMs = 10;
Could be float so we can set it w/ more granularity.
Also, should be syncTreshold?
Or adding a different std datatype that can take any format, seconds, ms, ns etc. (std chrono literals) ? Better ux
@moratom @themarpe

2023-11-20 12:33 UTC, szabi-luxonis commented on include/depthai-shared/properties/MessageDemuxProperties.hpp
> +    char dummy = 0;
I guess it can be left empty?

2023-11-20 12:47 UTC, asahtik commented on include/depthai-shared/properties/MessageDemuxProperties.hpp
> +    char dummy = 0;
I can't find a better way to get it working - If the struct is empty I cannot use the DEPTHAI_SERIALIZE macro (since there is no value to serialize). I could manually implement all the necessary methods but in my opinion that would be much uglier

2023-11-21 11:58 UTC, szabi-luxonis commented on include/depthai-shared/properties/SyncProperties.hpp
> +     * The maximal interval the messages can be apart in milliseconds.
need to change docs.

2023-11-28 10:45 UTC, themarpe approved these changes

2023-11-29 10:53 UTC, merged