Gen2: ImageManip rotated/arbitrary cropping
luxonis/depthai-shared pull request #16
Opened 2021-01-12 20:09 UTC by alex-luxonis

Add types defined similar to some OpenCV ones:
- `Point2f: {float x, y;}`
- `Size2f: {float width, height;}`
- `RotatedRect: {Point2f center; Size2f size; float angle;}`

And for arbitrary cropping, I was thinking on defining a sequence of 4 points in clockwise order forming a quadrilateral, that would get mapped to a rectangle, whose size we specify (so resizing + other transforms can be applied). First sequence point would get mapped to the top-left corner of the rectangle.
```
 0___1       0 ____ 1
 /   \   ->   |    |
/_____\       |____|
3     2      3      2
```

These are still open to ideas for improvement.

2021-01-13 10:43 UTC, themarpe commented
Does the intermediate rectangle size adds any additional benefits compared to just the final output size?

2021-02-08 11:00 UTC, alex-luxonis commented
> Does the intermediate rectangle size adds any additional benefits compared to just the final output size?

For the rotated rectangle (center, size, angle), it describes the crop area, that can be further resized.
For the quadrilateral (that I renamed it now to `warpFourPoints`), I removed the size specification, and it is auto-computed based on the points geometry, if the final resize is not specified.

2021-02-09 14:30 UTC, themarpe requested changes

2021-02-09 14:30 UTC, themarpe commented on include/depthai-shared/datatype/RawCameraControl.hpp
> +        if(value)
Either inline or with `{}`

2021-02-09 14:30 UTC, themarpe commented on include/depthai-shared/datatype/RawImageManipConfig.hpp
> +        float rotationAngle;
Could be `rotationAngleRad` or `rotationAngleDeg` and the `ImageManipConfig` wrapper calculates the correct value.
Then `angleInRadians` could be removed.
^ Only applicable if it affects this field only IMO

2021-02-09 14:43 UTC, alex-luxonis commented on include/depthai-shared/datatype/RawCameraControl.hpp
> +        if(value)
Wanted to have it inlined initially, but clangformat expanded it: 
https://github.com/luxonis/depthai-shared/pull/16/commits/2ece34cc5531147aa0b0f73f02e853211f17c061#diff-0c285f8d7cb2334c68a2f38b0fafa637d8be3e37cd4c2c072f03e7a2a505c75bL226
Will add `{}`

2021-02-09 14:43 UTC, alex-luxonis commented on include/depthai-shared/datatype/RawImageManipConfig.hpp
> +        float rotationAngle;
So I wanted to avoid this conversion math in the host library, but yeah, it's simple enough in this case that we can go with it. I think to go with degrees, as that's the case with most OpenCV API also.

2021-02-11 09:17 UTC, themarpe commented on include/depthai-shared/datatype/RawCameraControl.hpp
> +        if(value)
Saw that behaviour as well. Will have to check if I can modify clangformat for this case

2021-02-11 09:28 UTC, themarpe approved these changes

2021-02-12 14:24 UTC, merged