Eeprom api
luxonis/depthai-shared pull request #19
Opened 2021-02-05 05:12 UTC by saching13

This is just the basic idea I had for scenarios when there can be many cameras. in that situation. users have the flexibility to load and associate this calibration to any cameras(needs some changes). 
Things I am not sure about is whether we can use pointers like that?
should I replace it with camid / something else ?  

In gen1 we had `left_to_rgb distance` and `left_to_right distance`. if there are multiple cameras, or in the custom board, it doesn't make sense to use left or right since they can use any two cameras for stereo or any other tasks. So, I was thinking we should just mention it in extrinsic adding one more parameter as `measured_translation` or something like that. 

What do you guys think ? and what would be better to make it flexible like gen2.

2021-02-05 19:29 UTC, themarpe requested changes
Above remarks as well as there seems to be a merge issue.

2021-02-05 19:29 UTC, themarpe commented on include/depthai-shared/common/EepromData.hpp
> +    std::shared_ptr<CameraInfo> destCamera; // Does using pointer makes sense while writing to eeprom or should we just use an number index for cameras and link using that ?
I'd suggest using CameraBoardSocket as "id"

2021-02-05 19:29 UTC, themarpe commented on include/depthai-shared/common/EepromData.hpp
> +    std::shared_ptr<CameraInfo> *leftCamera, *rightCamera;
Here as well

2021-02-06 17:11 UTC, saching13 commented
@themarpe changed it to use CameraBoardSocket and added an extra var to `CameraBoardSocket` enum. and used it as the length of the camera rig. And also added a measured_translation variable. 

Another thing I wanted to discuss was fov variables. 
One thought I had was moving them inside the cameraInfo incase the custom boards might have different camera with different fov. 
Second was do we need to save it. it can be calculated using other intrinsics matrix right ? Does this apply to alll cameras for ex: wide/fisheye ? cc: @alex-luxonis

2021-02-08 10:02 UTC, themarpe requested changes

2021-02-08 10:02 UTC, themarpe commented on include/depthai-shared/common/CameraBoardSocket.hpp
> +enum class CameraBoardSocket : int32_t { AUTO = -1, RGB, LEFT, RIGHT, END };
I think we can go without `END` here and change the array to unordered map, as this is only data presentation.

2021-02-08 10:02 UTC, themarpe commented on include/depthai-shared/common/EepromData.hpp
> +    std::array<CameraInfo, CameraBoardSocket::END> cameraData;
`std::unordered_map<CameraBoardSocket, CameraInfo> cameraData`

2021-02-08 10:02 UTC, themarpe commented on include/depthai-shared/common/EepromData.hpp
> +    int16_t camera_rig_size = 3; // or we can use this for size of the array in cameraData
Is this suppose to present connected cameras? If so then we cannot be sure that they'll follow order.
Lets just deduct this size from `cameraData` map

2021-02-08 10:02 UTC, themarpe commented on include/depthai-shared/common/CameraBoardSocket.hpp
> +enum class CameraBoardSocket : int32_t { AUTO = -1, RGB, LEFT, RIGHT, END };
Or if really needed, I'd rather see `COUNT` or something a bit more out of context

2021-02-09 21:16 UTC, themarpe requested changes

2021-02-09 21:16 UTC, themarpe commented on include/depthai-shared/common/EepromData.hpp
> +struct point {
Create a `common/Point3f.hpp`, with `struct Point3f { float x,y,z; };`

2021-02-09 21:16 UTC, themarpe commented on include/depthai-shared/common/EepromData.hpp
> +    point measured_translation;
Use `camelCase`

2021-02-09 21:16 UTC, themarpe commented on include/depthai-shared/common/EepromData.hpp
> +    int baseline;
Should `baseline` rather be float?

2021-02-09 21:16 UTC, themarpe commented on include/depthai-shared/common/EepromData.hpp
> +    std::string board_name, board_rev;
Use `camelCase`

2021-03-16 19:28 UTC, alex-luxonis commented on include/depthai-shared/common/EepromData.hpp
> +    std::vector<std::vector<float>> rectifiedRotationLeft, rectifiedRotationRight;
Thinking about being able to do StereoDepth between any cameras (even RGB + Mono), should we move the `rectifiedRotation` matrix to `CameraInfo`? Currently I also don't see the RGB rotation matrix specified.

2021-03-17 16:24 UTC, saching13 commented on include/depthai-shared/common/EepromData.hpp
> +    std::vector<std::vector<float>> intrinsicMatrix;
Yes. I think it would be good to add width and height which will act as a reference for at what res calibration was added. Will add that. Thanks for pointing it out.  
And as of FOV from specs I have already added that for the same reason.

2021-03-17 16:36 UTC, saching13 commented on include/depthai-shared/common/EepromData.hpp
> +    std::vector<std::vector<float>> rectifiedRotationLeft, rectifiedRotationRight;
RGB doesn't have rectification rotation. 
And rectification is relative to the other camera so it would require us to have rectification between left/right, right/rgb, and left/right making up to 6 matrixes on OBC case and more if we have 4 or more cameras. 
So Stereo Rectification will have for the defaults that we computed. 
And rectification for other can be computed by using [this](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga617b1685d4059c6040827800e72ad2b6) algorithm. we can recreate this or use it on the host side to pass the obtained rectification, cameras using overload functions like
overleadLeftRectification/ overloadRIghtRectification. 

And as of `baseline`, it seems redundant. will remove it.

2021-04-02 21:44 UTC, themarpe requested changes
`matrixOps.hpp` shouldn't reside in shared.
Use appropriate library on both FW side and in `core`
Maybe Eigen might be a good one to checkout?: https://hunter.readthedocs.io/en/latest/packages/pkg/Eigen.html

2021-04-02 22:53 UTC, saching13 commented
MatrixOps contains only matrix multiplication and inverse and these two are used on both firmware and on device side. 
I thought of using Eigen, but it didn't make sense to add the lib just for multiplication and inverse. 
So may be if we start using more functionalities then we can move to Eigen. 

Thoughts ?

2021-04-03 00:03 UTC, themarpe commented
> MatrixOps contains only matrix multiplication and inverse and these two are used on both firmware and on device side.
> I thought of using Eigen, but it didn't make sense to add the lib just for multiplication and inverse.
> So may be if we start using more functionalities then we can move to Eigen.
> 
> Thoughts ?

You can add it to core and FW separately for now if needed before Eigen or some other library.

The rational is that `depthai-shared` houses only needed data structures (with minimal supporting code) to facilitate communication between FW and host. 
Borderline case is `nanorpc` which would probably land as a separate library in both FW & host if not for many customizations needed to make it work on both ends.

2021-04-03 00:20 UTC, saching13 commented
Ah okay. My bad. I thought any helper codes that are shared between core and HW can be added here.

2021-05-11 16:29 UTC, alex-luxonis commented on include/depthai-shared/common/EepromData.hpp
> +    bool swapLeftRightCam = false;
About this parameter, currently it is unused. Should we remove it, or if implemented, where should it take effect:
- directly in swapping the LEFT and RIGHT camera board sockets
- inside the StereoDepth node, and then should it be moved to StereoRectification

Also it's a bit confusing as in the existing json configs (e.g [here for OAK-D](https://github.com/luxonis/depthai/blob/eaa15f1/resources/boards/BW1098OBC.json#L6)) is was inverted, due to some historical reasons. 

Thoughts @saching13 @szabi-luxonis @themarpe ?

2021-05-11 16:29 UTC, alex-luxonis commented on include/depthai-shared/common/Extrinsics.hpp
> +    Point3f measuredTranslation;
Another note on the naming here, does it makes sense to replace `measuredTranslation` with `designTranslation` (or `specTranslation`). Just because when actually _measured_, it could be slightly off due to mounting, even though the comment says exactly what it does.

2021-05-11 16:29 UTC, alex-luxonis commented on include/depthai-shared/common/Extrinsics.hpp
> +    CameraBoardSocket fromCameraSocket = CameraBoardSocket::AUTO;
Just to clarify my understanding, here `fromCameraSocket` need to match with the socket from the `EepromData::cameraData` map?
And is the above comment still actual, or can be removed.

2021-05-11 16:40 UTC, saching13 commented on include/depthai-shared/common/CameraInfo.hpp
> +    float measuredFovDeg = 0.0f;  // fov in deg
good idea. Will change that.

2021-05-11 16:45 UTC, saching13 commented on include/depthai-shared/common/EepromData.hpp
> +    bool swapLeftRightCam = false;
> directly in swapping the LEFT and RIGHT camera board sockets

I like this idea than specifying but it would make it confusing since LEFT and RIGHT is used for naming board sockets. 
It would be good to add alternative naming for them based on which port is connected. For ex: something like CM1, CM2, CM3 etc. 
This would help in better readability of code too when users build custom boards on top of ours or use different Camera Socket on FCC module. 

Thoughts ?

2021-05-11 16:46 UTC, saching13 commented on include/depthai-shared/common/Extrinsics.hpp
> +    CameraBoardSocket fromCameraSocket = CameraBoardSocket::AUTO;
I am not using `fromCameraSocket` anymore. Will be removing it before merge.

2021-05-11 20:06 UTC, saching13 commented on include/depthai-shared/common/CameraBoardSocket.hpp
> +}  // namespace std
But agree. 
We can change it to min C++14 on cmake and give it a shot on mac and see.

2021-05-11 21:04 UTC, themarpe commented on include/depthai-shared/common/EepromData.hpp
> +    bool swapLeftRightCam = false;
I'm up for moving this into a more appropriate place. It also doesn't have to be explicitly mentioned as upgrading old calibrations can just set the calibration data correctly (or swapping them when setting) and this information will be "upgraded".

Maybe an issue is if we don't want to reflash but still move calibration data around? But probably won't happen much to be an issue to just reflash the eeprom. And with current API that should be possible to swap calib data between two sockets right?

2021-05-18 20:35 UTC, saching13 commented
Any more suggestions here? 
I am thinking of finalizing this V6 version and update the `gen2_uvc_calib` branch which will be used for arm calibration for rgb-left setup.

2021-05-19 20:41 UTC, saching13 commented on include/depthai-shared/common/EepromData.hpp
> +    bool swapLeftRightCam = false;
For V5 calibration already stored I don't think we need to reflash. I can read it left and right and load it appropriately based on swap mode for that instance.

2021-05-19 20:42 UTC, saching13 commented on include/depthai-shared/common/EepromData.hpp
> +    bool swapLeftRightCam = false;
and yeah looks like we can remove it from V6

2021-05-19 22:18 UTC, saching13 commented on include/depthai-shared/common/EepromData.hpp
> +    bool swapLeftRightCam = false;
cc: @alex-luxonis  @themarpe

2021-05-19 23:01 UTC, alex-luxonis commented on include/depthai-shared/common/EepromData.hpp
> +    bool swapLeftRightCam = false;
I'm also inclined towards removing this field. During calibration we can detect if the cameras are swapped and warn the user, and can have an option to calibrate with the cameras swapped. And the swapping can be deduced later in FW from the extrinsics translation vector orientation. I'm just not sure if we should have the user swap the `left` and `right` inputs linked to StereoDepth, or we should do this internally inside the node.

2021-05-20 03:07 UTC, saching13 commented on include/depthai-shared/common/EepromData.hpp
> +    bool swapLeftRightCam = false;
Hhmm. 
I am also inclined to remove it. Since I prefer if `CameraSocketBoard` represents a specific port instead of which camera in a stereo setup to avoid more confusion in the future.

if it's okay with everyone I will go ahead and remove it and swap left and right for v5 internally. And during calibration. 
And stereo rectification of calibration part will contain which socket is left and which socket is right which we can validate and throw a warning/error if the user sets the stereo inputs differently.

Thoughts ? cc: @alex-luxonis  @themarpe  @szabi-luxonis

2021-05-20 13:42 UTC, themarpe commented on include/depthai-shared/common/EepromData.hpp
> +    bool swapLeftRightCam = false;
I agree as well - CameraBoardSocket represents the port (with convenient naming of current HW positioning) so IMO this option shouldn't be needed.

2021-05-28 05:00 UTC, saching13 commented
If all good with the structure. I will go ahead with the merging tomorrow. 
cc: @alex-luxonis  @themarpe  @szabi-luxonis

2021-05-28 15:21 UTC, alex-luxonis approved these changes

2021-05-29 00:15 UTC, saching13 commented on include/depthai-shared/common/CameraBoardSocket.hpp
> +}  // namespace std
```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

I tried setting this in CMakeLists.txt on mac and removed the hash but didn't work.

2021-05-30 03:02 UTC, merged

2021-05-31 10:23 UTC, themarpe commented on include/depthai-shared/common/CameraBoardSocket.hpp
> +}  // namespace std
Thanks for the test!

2021-05-31 16:47 UTC, alex-luxonis commented on include/depthai-shared/common/CameraBoardSocket.hpp
> +}  // namespace std
It does work for me, with this on Mac (printed by cmake):
`-- The CXX compiler identification is AppleClang 12.0.0.12000032`

Tested with: https://github.com/luxonis/depthai-core/commit/ad000a87d197802605df760a08c76c09857e11c8
(note that in `depthai-core/CMakeLists.txt` the C++ standard version is set differently, this may have overwritten CMAKE_CXX_STANDARD.

Also CI is passing: https://github.com/luxonis/depthai-core/actions/runs/893501003

2021-05-31 17:03 UTC, saching13 commented on include/depthai-shared/common/CameraBoardSocket.hpp
> +}  // namespace std
Yeah. you are right. it was overwritten. Thanks for crosschecking.