Integrated Intel's object tracker, added spatial object tracker
luxonis/depthai-shared pull request #25
Opened 2021-03-25 19:46 UTC by szabi-luxonis

2021-03-25 22:37 UTC, themarpe requested changes

2021-03-25 22:37 UTC, themarpe commented on include/depthai-shared/datatype/RawTracklets.hpp
> +}
I'd rather move this to `Tracklet` in core.

2021-03-25 22:37 UTC, themarpe commented on include/depthai-shared/datatype/RawTracklets.hpp
> +    Point3f spatialCoordinates;
Add docstrings for these as well

2021-03-25 22:37 UTC, themarpe commented on include/depthai-shared/common/Point2f.hpp
> +    Point2f() : x(0), y(0) {}
Should we rather do 
```
float x = 0, y = 0;
```
And leave constructor as default (no need to specify it)?

2021-03-25 22:37 UTC, themarpe commented on include/depthai-shared/common/Point3f.hpp
> +    Point3f() : x(0), y(0), z(0) {}
Should we rather do 
```
float x = 0, y = 0, z = 0;
```
And leave constructor as default (no need to specify it)?

2021-03-30 15:42 UTC, szabi-luxonis commented on include/depthai-shared/datatype/RawTracklets.hpp
> +}
Then we won't have access to this on device, where we only include `RawTracklets.hpp`. Not a big deal but I see this bound to `Tracklet` structure.

2021-03-30 21:55 UTC, themarpe commented on include/depthai-shared/datatype/RawTracklets.hpp
> +}
Main idea behind suggestion is to minimize "non essential code / data" in depthai-shared, to decouple FW and depthai-core more in case of changes.

Up to you, either is okay - nothing major

2021-03-30 21:55 UTC, themarpe approved these changes

2021-04-05 21:15 UTC, merged