Gen2 apriltag
luxonis/depthai-shared pull request #42
Opened 2021-06-28 00:02 UTC by csaba-luxonis

WIP. Currently it runs on full frame with ~6 fps, with image manip it could be 30+ but it does not support it yet, the previous scaling was pretty bad (skipped pixels in order to scale down the image).

2021-06-28 15:10 UTC, themarpe requested changes
Consolidate naming. 
eg: `RawAprilTags` -> `AprilTagData` <- should be the same, just the Raw prepended. 

Also `AprilTagConfigData` is too close to AprilTagConfig (config message) or AprilTagData (data  message). Pick something else or expose otherwise. 

(Maybe: AprilTagThresholds & AprilTagType, which are then used by RawAprilTagConfig as members separatelly)

Otherwise AprilTag for the name of the node and AprilTagProperties for its properties is :ok_hand:

2021-06-28 15:10 UTC, themarpe commented on include/depthai-shared/datatype/RawAprilTags.hpp
> +    float decision_margin;
decisionMargin

2021-06-28 15:10 UTC, themarpe commented on include/depthai-shared/datatype/RawAprilTags.hpp
> +    dai::Rect p;
Use full names here - eg: `c` -> `center`
Same for `p` abbreviation

2021-06-28 15:10 UTC, themarpe commented on include/depthai-shared/datatype/RawAprilTags.hpp
> +struct AprilTags {
`struct AprilTag` IMO

2021-07-06 19:56 UTC, themarpe requested changes

2021-07-06 19:56 UTC, themarpe commented on include/depthai-shared/datatype/RawAprilTagConfig.hpp
> +NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(AprilTagType, t);
Can just be:
```
enum class AprilTagType : std::int32_t { TAG_36H11 = 0, TAG_25H9, TAG_16H5, TAG_CIR21H7, TAG_CIR49H12, TAG_CUST48H12, TAG_STAND41H12, TAG_STAND52H13 };
```

2022-01-31 03:07 UTC, merged

2022-01-31 10:15 UTC, themarpe commented on include/depthai-shared/datatype/RawAprilTags.hpp
> +struct AprilTags {
@szabi-luxonis 
Address this issue as well

2022-01-31 10:18 UTC, themarpe reviewed
Please address the comments left as part of the response to the OP of the PR

2022-01-31 10:18 UTC, themarpe commented on include/depthai-shared/datatype/DatatypeEnum.hpp
> +    AprilTagData,
`AprilTags`

2022-01-31 10:18 UTC, themarpe commented on src/datatype/DatatypeEnum.cpp
> +         DatatypeEnum::AprilTagData,
AprilTags

2022-01-31 10:18 UTC, themarpe commented on src/datatype/DatatypeEnum.cpp
> +    {DatatypeEnum::AprilTagData, {}},
AprilTags

2022-01-31 12:00 UTC, szabi-luxonis commented on include/depthai-shared/datatype/RawAprilTags.hpp
> +struct AprilTags {
AprilTag is the name of the node

2022-01-31 12:54 UTC, themarpe commented on include/depthai-shared/datatype/RawAprilTags.hpp
> +struct AprilTags {
Does it cause a conflict?