Feature tracking support
luxonis/depthai-shared pull request #48
Opened 2021-07-20 01:34 UTC by szabi-luxonis

2021-07-21 08:49 UTC, themarpe requested changes

2021-07-21 08:49 UTC, themarpe commented on include/depthai-shared/datatype/RawFeatureTrackerConfig.hpp
> +NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(FeatureTrackerConfigData, dummy);
Unnecessary IMO, rather just list properties in message itself (`RawFeatureTrackerConfig`)

2021-07-21 08:49 UTC, themarpe commented on include/depthai-shared/datatype/RawTrackedFeatures.hpp
> +struct TrackedFeatures {
`TrackedFeature`

2021-07-21 08:49 UTC, themarpe commented on include/depthai-shared/datatype/RawTrackedFeatures.hpp
> +    };
Rename the enum to be `TrackedFeatures` as is the message name

2021-07-21 09:15 UTC, szabi-luxonis commented on include/depthai-shared/datatype/RawFeatureTrackerConfig.hpp
> +NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(FeatureTrackerConfigData, dummy);
It's a stub, will be implemented later.

2021-07-21 09:24 UTC, szabi-luxonis commented on include/depthai-shared/datatype/RawFeatureTrackerConfig.hpp
> +NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(FeatureTrackerConfigData, dummy);
```
sizeof(dai::FeatureTrackerConfigData) = 4
sizeof(dai::RawFeatureTrackerConfig) = 40
```

So it's significantly larger.
In this case it's not a huge issue, but in other cases where the output is a vector of that type it's a waste of space.
Should we rename `RawX` to `XMessage` ?

2021-07-21 11:42 UTC, themarpe commented on include/depthai-shared/datatype/RawFeatureTrackerConfig.hpp
> +NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(FeatureTrackerConfigData, dummy);
I see the rationale behind, its just a tad weird naming and structure wise to have that as a separate structure.
If possible to go without and then create a config message from properties without having to store the whole message, that'd be best.

I'd rather put messages under `dai::message::X` than explicitly name them with `XMessage`. Also the Raw has to remain in some way or another, we could put it under `dai::message::raw` or `dai::raw` or something else, and name same as those in core, but we still need the differentiation, between core wrappers and raw shared messages.

2021-07-22 14:56 UTC, alex-luxonis commented on include/depthai-shared/datatype/RawFeatureTrackerConfig.hpp
> +     * maximum number of features is determined at runtime based on algorithm type
Needs some punctuation here, or an extra empty line (just with `*`), as the docs generator concatenates the lines otherwise:
![image](https://user-images.githubusercontent.com/60824841/126660680-df64fec2-e927-4ce4-b73b-67e2d8bddf2d.png)

2021-07-22 15:02 UTC, alex-luxonis commented on include/depthai-shared/datatype/RawFeatureTrackerConfig.hpp
> +struct RawFeatureTrackerConfig : public RawBuffer {
Update comment name (copied probably).

2021-07-26 10:54 UTC, szabi-luxonis commented on include/depthai-shared/datatype/RawTrackedFeatures.hpp
> +    };
The message in `depthai-core` is named as `FeatureTrackerData`

2021-07-28 21:56 UTC, themarpe approved these changes
LGTM - apart of offline discussion regarding `FeatureTrackerConfigData`, TBD

2021-07-31 08:03 UTC, alex-luxonis reviewed
Just some minor typos I noticed. Would be good to be fixed, to not get into docs.

2021-08-10 20:06 UTC, merged