Add ISP 3A camera controls
luxonis/depthai-shared pull request #5
Opened 2020-09-28 21:58 UTC by alex-luxonis

2020-09-28 22:34 UTC, szabi-luxonis requested changes

2020-09-28 22:34 UTC, szabi-luxonis commented on include/depthai-shared/metadata/camera_control.hpp
> +enum Isp3A_CamId : int {
use `int32_t` instead

2020-09-28 22:34 UTC, szabi-luxonis commented on include/depthai-shared/metadata/camera_control.hpp
> +enum Isp3A_Commands : int {
use int32_t instead

2020-10-06 00:03 UTC, themarpe requested changes
Having `enum class` you can probably shorten the enums as they are encapulated in the name of the enum class. Eg `AutoFocusMode::AF_AUTO` -> `AutoFocusMode::AUTO`

Also consider serialization from depthai-core PR

2020-10-07 21:13 UTC, merged