Fetching USB speed and Myriad X serial number
luxonis/depthai-shared pull request #7
Opened 2020-10-12 23:11 UTC by saching13

Modified `initFromHostSide` to take `usb_speed` and `mx_serial` strings as arguments(pass by reference) which are private variables of device class. allowing them to be loaded on XLink connection.

2020-11-04 22:48 UTC, szabi-luxonis requested changes

2020-11-04 22:48 UTC, szabi-luxonis commented on src/xlink/xlink_wrapper.cpp
> +    char dev_conn_info[148] = { 0 };
this is unused?

2020-11-04 22:48 UTC, szabi-luxonis commented on src/xlink/xlink_wrapper.cpp
> +        printf("firmware sent\n");
I assume this is just debug print?

2020-11-04 22:48 UTC, szabi-luxonis commented on src/xlink/xlink_wrapper.cpp
> +XLinkError_t XLinkWrapper::connect(XLinkHandler_t* handler){
can you rename it to `XLinkConnectSafe` or something similar, so it's clear that it's just a wrapper ?

2020-11-04 23:21 UTC, saching13 commented on src/xlink/xlink_wrapper.cpp
> +        printf("firmware sent\n");
Yes. yes. I haven't cleaned this one yet. let me clean it up. :)

2020-11-05 04:32 UTC, szabi-luxonis approved these changes
LGTM

2020-11-05 11:10 UTC, themarpe commented on src/xlink/xlink_wrapper.cpp
> +std::string XLinkWrapper::getUSBSpeed(){
Return UsbSpeed_t here, and create a separate function which outputs usb speed as string (if needed).
And modify this: https://github.com/luxonis/depthai-core/pull/14/files#r517970300

2020-11-06 02:18 UTC, merged